#!/usr/bin/env bash
rsync --omit-dir-times --delete-after -zave ssh --progress --exclude public/media --exclude public/js/src --exclude node_modules /home/christian/Documents/acw christian@chrisamaral.me:/home/christian/
rsync --omit-dir-times --delete-after -zave ssh --progress --exclude node_modules /home/christian/Documents/me christian@chrisamaral.me:/home/christian/
